export { WqaOverviewTab } from './OverviewTab'
export { WqaActionsTab } from './ActionsTab'
export { WqaSearchTab } from './SearchTab'
export { WqaTechTab } from './TechTab'
export { WqaContentTab } from './ContentTab'
